language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

install:
 - composer install
script:
  - bin/phpunit
  - bin/phpcs --standard=PSR2 --error-severity=1 --warning-severity=8 src tests
after_success:
  - bin/test-reporter --coverage-report=build/logs/clover.xml

