options:
  limit:
    name: limit
    alias: l
    optional: true
    description: 'How many issues should be printed ?'
    default: 10
  sort:
    name: sort
    alias: s
    optional: true
    description: 'Issues sorting'
    default: 'updated_on:desc'
  project_id:
    name: project_id
    alias: ~
    optional: true
    description: 'Filter by project machine name'
    default: ~
  category-id:
    name: category_id
    alias: ~
    optional: true
    description: 'Filter by project category'
    default: ~
  tracker-id:
    name: tracker_id
    alias: ~
    optional: true
    description: 'Filter by tracker id'
    default: ~
  status-id:
    name: status_id
    alias: ~
    optional: true
    description: 'Filter by project status id'
    default: ~
  assigned-to-id:
    name: assigned_to_id
    alias: a
    optional: true
    description: 'Filter by assignet to user id'
    default: me

