options:
  report:
    name: report
    alias: ~
    optional: none
    description: 'Print a summary report'
  limit:
    name: limit
    alias: l
    optional: true
    description: 'How many issues should be printed ?'
    default: 50
  sort:
    name: sort
    alias: s
    optional: true
    description: 'Issues sorting'
    default: 'updated_on:desc'
  project_id:
    name: project_id
    alias: p
    optional: true
    description: 'Filter by project machine name'
    default: ~
  status:
    name: status
    alias: ~
    optional: true
    description: 'Filter by project status id'
    default: open
  assigned:
    name: assigned
    alias: ~
    optional: true
    description: 'Filter by assigned to user id or by user name'
    default: me
  version:
    name: sprint
    alias: ~
    optional: true
    description: 'Filter by version (sprint name). You can specify name (ex: SPRINT-XX) or numeric-id.'
    default: ~
  #category:
  #  name: category_id
  #  alias: c
  #  optional: true
  #  description: 'Filter by project category'
  #  default: ~
  #tracker:
  #  name: tracker_id
  #  alias: t
  #  optional: true
  #  description: 'Filter by tracker id'
  #  default: ~


